services:
 leash-backend:
  container_name: leash-backend-prd
  ports:
   - 3001:3001
  build:
   context: .
   dockerfile: Dockerfile
  volumes:
   - /app:/usr/src/app/       
   - /usr/src/app/node_modules
   - /usr/src/app/.next
  env_file:
   - secretAccessKey: 4m2pW+k44Q3xGLFUC2pAB3/ii3uu77cV/wRFXgTi
   - accessKeyId: AKIAZLBHUHLT5TTJZV5M
   - TOKEN_KEY: 1234
   - ADMIN_KEY: aa19ed1b63955f17719f52103455f00d
   - DB: mongodb://leashposts:leashmasterposts@leash-shard-00-00.t5u93.mongodb.net:27017,leash-shard-00-01.t5u93.mongodb.net:27017,leash-shard-00-02.t5u93.mongodb.net:27017/Leash?ssl=true&replicaSet=atlas-gbs8j9-shard-0&authSource=admin&retryWrites=true&w=majority